function dualMat = DualVecToMat(in1)
%DUALVECTOMAT
%    DUALMAT = DUALVECTOMAT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Dec-2017 16:00:35

d1 = in1(1,:);
d2 = in1(2,:);
d3 = in1(3,:);
d4 = in1(4,:);
d5 = in1(5,:);
d6 = in1(6,:);
d7 = in1(7,:);
d8 = in1(8,:);
d9 = in1(9,:);
d10 = in1(10,:);
t2 = d10.*(1.0./2.0);
t3 = d9.*(1.0./2.0);
t4 = d8.*(1.0./2.0);
t5 = d3.*(1.0./4.0);
t6 = d4.*(1.0./4.0);
t7 = d2.*(1.0./4.0);
t8 = d1.*(1.0./3.0);
dualMat = reshape([d5,t2,t3,0.0,-t6,t5,t2,d6,t4,t6,0.0,-t7,t3,t4,d7,-t5,t7,0.0,0.0,t6,-t5,t8,0.0,0.0,d4.*(-1.0./4.0),0.0,t7,0.0,t8,0.0,t5,d2.*(-1.0./4.0),0.0,0.0,0.0,t8],[6,6]);
